# Generated by Django 3.1 on 2020-09-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='category',
            field=models.TextField(default='без категории'),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='description',
            field=models.TextField(default='Описание отсуктсвует'),
        ),
    ]
