# Generated by Django 3.1 on 2020-09-06 16:39

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200906_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('category_image', models.ImageField(upload_to='F:\\workspace\\python\\test_proj\\media')),
                ('category_description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[shop.models.validate_name])),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=100)),
                ('phone', models.CharField(max_length=14)),
            ],
        ),
    ]
