# Generated by Django 3.1 on 2020-09-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_categories_feedbackmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='shopitem',
            name='category',
        ),
        migrations.AddField(
            model_name='categories',
            name='category_url',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='category_name',
            field=models.TextField(default='Без категории', null=True),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='url_title',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='category_image',
            field=models.ImageField(null=True, upload_to='F:\\workspace\\python\\test_proj\\media'),
        ),
    ]
