# Generated by Django 3.1 on 2020-09-07 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200907_1734'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoriesModel',
        ),
        migrations.AddField(
            model_name='shopitem',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
