# Generated by Django 3.1 on 2020-09-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200910_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='comments',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
