# Generated by Django 3.1 on 2020-09-10 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_feedbackmodel_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoriesModel',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='category_description',
        ),
    ]
