# Generated by Django 3.1 on 2020-09-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200911_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='image_big',
            field=models.ImageField(null=True, upload_to='F:\\workspace\\python\\test_proj\\media'),
        ),
    ]
