# Generated by Django 3.1 on 2020-09-20 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_shopitem_image_big'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('url_title', models.CharField(max_length=32, null=True)),
                ('description', models.TextField(default='Описание отсутсвует')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('image', models.ImageField(upload_to='F:\\workspace\\python\\test_proj\\media')),
                ('image_big', models.ImageField(null=True, upload_to='F:\\workspace\\python\\test_proj\\media')),
                ('category_name', models.TextField(default='Без категории', null=True)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product'),
        ),
        migrations.DeleteModel(
            name='ShopItem',
        ),
    ]
