# Generated by Django 3.1 on 2020-09-21 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200921_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeds',
            name='news_body',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='feeds',
            name='news_image',
            field=models.ImageField(upload_to='F:\\workspace\\python\\test_proj\\media'),
        ),
        migrations.AlterField(
            model_name='feeds',
            name='news_post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='feeds',
            name='title',
            field=models.CharField(max_length=32),
        ),
    ]
