# Generated by Django 3.1 on 2020-09-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20200921_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeds',
            name='news_big_image',
            field=models.ImageField(null=True, upload_to='F:\\workspace\\python\\test_proj\\media'),
        ),
    ]
