# Generated by Django 3.1 on 2020-10-16 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_feeds_news_big_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
